#print("hello python")
#name = input("please enter your name: ")
#print(len(name))
#name = name.replace(" ", "") 
#print(len(name))
a = input("enter first string A: ")
b = input("enter second string B: ")
c = input("enter third string C: ")
d = input("enter forth string D: ")
e= input("enter fifth string E: ")
a = a.replace(" ", "")
b = b.replace(" ", "")
c = c.replace(" ", "")
d = d.replace(" ", "")
e = e.replace(" ", "")
print("length of A= ", len(a), "length of B= ", len(b), "length of C= ", len(c), "length of D= ", len(d), "length of E= ", len(e))
